### ISSUE TITLE
Openstack Keystone integration

### ISSUE THREAD

**Issue by ekarlso** [platformlayer/platformlayer#9]
Does it integrate with ks ?

Endre.

**Comment by justinsb** [comment]
Sorry for the delay in responding!

PlatformLayer can use OpenStack, so it can act as a Keystone client.  This code is mostly in the openstack-java project.

PlatformLayer also includes an authentication system, which originally was a re-implementation of the Keystone API.  However, over time it evolved to include additional features that Keystone does not offer, in particular cryptographic key management.  It is my hope that Keystone will include these features eventually, but at the moment the PlatformLayer system is not compatible with Keystone.  It is still called Keystone in many places though - that should probably get fixed!
